name: Build

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

defaults:
  run:
    shell: bash

env:
  SCM_LOCAL_SCHEME: no-local-version

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest,   python: 3.8,  arch: x64 }
          - { os: ubuntu-latest,   python: 3.7,  arch: x64 }
          - { os: ubuntu-latest,   python: 3.6,  arch: x64 }

          - { os: macos-latest,    python: 3.8,  arch: x64 }
          - { os: macos-latest,    python: 3.7,  arch: x64 }
          - { os: macos-latest,    python: 3.6,  arch: x64 }

          - { os: windows-latest,  python: 3.8,  arch: x64 }
          - { os: windows-latest,  python: 3.7,  arch: x64 }
          - { os: windows-latest,  python: 3.6,  arch: x64 }

          - { os: windows-latest,  python: 3.8,  arch: x86 }
          - { os: windows-latest,  python: 3.7,  arch: x86 }
          - { os: windows-latest,  python: 3.6,  arch: x86 }

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Ignore Tags
      if: github.event.ref_type != 'tag'
      run: git tag -d $(git tag --points-at HEAD)

    - if: github.event.ref_type != 'tag'
      run: git tag -d $(git tag --points-at HEAD)

    - name: Download Conda installer
      run: |
        if [ $RUNNER_OS == Windows ] && [ ${{ matrix.arch }} == x64 ]; then
            CONDA_INSTALLER=Miniconda3-latest-Windows-x86_64.exe
        elif [ $RUNNER_OS == Windows ]; then
            CONDA_INSTALLER=Miniconda3-latest-Windows-x86.exe
        elif [ $RUNNER_OS == Linux ]; then
            CONDA_INSTALLER=Miniconda3-latest-Linux-x86_64.sh
        else
            CONDA_INSTALLER=Miniconda3-latest-MacOSX-x86_64.sh
        fi
        curl -LO "https://repo.continuum.io/miniconda/$CONDA_INSTALLER" 
        echo "::set-env name=CONDA_INSTALLER::$CONDA_INSTALLER"

    - name: Build Conda package (Unix)
      if: runner.os != 'Windows'
      run: |
        bash "$CONDA_INSTALLER" -b -p .miniconda
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        conda update -n base -c defaults conda
        conda create -n py${{ matrix.python }} python=${{ matrix.python }}
        conda activate py${{ matrix.python }}
        python -m setuptools_conda build .

    - name: Build Conda Package (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        %CONDA_INSTALLER% /S /D=%CD%\.miniconda && ^
        .miniconda\Scripts\activate && ^
        conda update -n base -c defaults conda && ^
        conda create -n py${{ matrix.python }} python=${{ matrix.python }} && ^
        conda activate py${{ matrix.python }} && ^
        python -m setuptools_conda build .
    
    - uses: actions/upload-artifact@v1
      with:
        name: conda_packages
        path: ./conda_packages

  upload:
    name: Upload to Anaconda Cloud
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: conda_packages
        path: ./conda_packages

    - name: Install Miniconda and cloud client
      run: |
        curl -LO "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" 
        bash Miniconda3-latest-Linux-x86_64.sh -b -p .miniconda
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        conda install anaconda-client

    - name: Upload to test label
      if: github.event.ref_type != 'tag'
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        anaconda \
          --token ${{ secrets.ANACONDA_API_TOKEN }} \
          upload \
          --user labscript-suite \
          --label test \
          conda_packages/*/*
          
    - name: Upload to main label
      if: github.event.ref_type == 'tag'
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        anaconda \
          --token ${{ secrets.ANACONDA_API_TOKEN }} \
          upload \
          --user labscript-suite \
          conda_packages/*/*
