name: Build

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

defaults:
  run:
    shell: bash

env:
  SCM_LOCAL_SCHEME: no-local-version

jobs:
  build:
    name: Conda Build
    runs-on: ubuntu-latest
    if: github.repository == 'chrisjbillington/setuptools-conda' && (github.event_name != 'create' || github.event.ref_type != 'branch')
    steps:
    - uses: actions/checkout@v2
    - if: github.event.ref_type != 'tag'
      run: |
        git fetch --prune --unshallow
        git tag -d $(git tag --points-at HEAD)

    - name: Install Miniconda
      run: |
        curl -LO "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" 
        bash Miniconda3-latest-Linux-x86_64.sh -b -p .miniconda

    - name: Build conda package
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        python -m setuptools_conda build .
    
    - uses: actions/upload-artifact@v1
      with:
        name: conda_packages
        path: ./conda_packages


  upload:
    name: Upload to Anaconda Cloud
    runs-on: ubuntu-latest
    needs: build
    env:
      MINICONDA: 
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: conda_packages
        path: ./conda_packages

    - name: Install Miniconda and Cloud client
      run: |
        curl -LO "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" 
        bash Miniconda3-latest-Linux-x86_64.sh -b -p .miniconda
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        conda install anaconda-client

    - name: Upload to test label
      if: github.event.ref_type != 'tag'
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        anaconda \
          --token ${{ secrets.ANACONDA_API_TOKEN }} \
          upload \
          --user cbillington \
          --label test \
          conda_packages/*/*
          
    - name: Upload to main label
      if: github.event.ref_type == 'tag'
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        anaconda \
          --token ${{ secrets.ANACONDA_API_TOKEN }} \
          upload \
          --user cbillington \
          conda_packages/*/*