name: Build

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Conda Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          miniconda: Miniconda3-latest-Windows-x86_64.exe
        - os: windows-latest
          miniconda: Miniconda3-latest-Windows-x86.exe
        - os: ubuntu-latest
          miniconda: Miniconda3-latest-Linux-x86_64.sh
        - os: macos-latest
          miniconda: Miniconda3-latest-MacOSX-x86_64.sh

    env:
      SCM_LOCAL_SCHEME: no-local-version

    steps:
    - uses: actions/checkout@v2
    - if: github.event.ref_type != 'tag'
      run: |
        git fetch --prune --unshallow
        git tag -d $(git tag --points-at HEAD)

    - name: Download miniconda
      run: curl -LO "https://repo.continuum.io/miniconda/${{ matrix.miniconda }}" 
    - name: Install miniconda (Windows)
      if: matrix.os == 'windows-latest'
      # Args aren't passed correctly to the miniconda installer unless run with cmd.exe:
      run:  cmd //C "${{ matrix.miniconda }} /S /D=%CD%\.miniconda"
    - name: Install miniconda (Unix)
      if: matrix.os != 'windows-latest'
      run:  bash "${{ matrix.miniconda }}" -b -p .miniconda

    - name: Build conda packages
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        conda install conda-build conda-verify importlib_metadata setuptools_scm ripgrep
        python setup.py dist_conda
    
    - uses: actions/upload-artifact@v1
      with:
        name: conda_packages
        path: ./conda_packages


  upload:
    name: Upload to Anaconda Cloud
    runs-on: ubuntu-latest
    needs: build
    env:
      MINICONDA: Miniconda3-latest-Linux-x86_64.sh
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: conda_packages
        path: ./conda_packages

    - name: Install Miniconda and cloud client
      run: |
        curl -LO "https://repo.continuum.io/miniconda/$MINICONDA" 
        bash "$MINICONDA" -b -p .miniconda
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        conda install anaconda-client

    - name: Upload to test label
      if: github.event.ref_type != 'tag'
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        anaconda \
          --token ${{ secrets.ANACONDA_API_TOKEN }} \
          upload \
          --user cbillington \
          --label test \
          conda_packages/*/*
          
    - name: Upload to main label
      if: github.event.ref_type == 'tag'
      run: |
        source .miniconda/etc/profile.d/conda.sh
        conda activate
        anaconda \
          --token ${{ secrets.ANACONDA_API_TOKEN }} \
          upload \
          --user cbillington \
          conda_packages/*/*